# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

title: oscarmcm.com
description: oscarmcm.com
author:
  name: oscarmcm.com
  email: om.cortez.2010@gmail.com

# baseurl: "/blog" # the subpath of your site, e.g. /blog/
# url: "http://localhost:8000" # the base hostname & protocol for your site

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true


pygments: true
